[package]
name = "filler_killer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
curl = "0.4.38"
regex = "1.5.4"
serde = "1.0.130"
terminal-menu = "2.0.0"
youtube_dl = "0.6.2"
